# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avtoriz2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 364)
        Form.setStyleSheet("background-color: rgb(231, 255, 212);")
        self.label_avtorizazia = QtWidgets.QLabel(Form)
        self.label_avtorizazia.setGeometry(QtCore.QRect(80, 40, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_avtorizazia.setFont(font)
        self.label_avtorizazia.setStyleSheet("")
        self.label_avtorizazia.setObjectName("label_avtorizazia")
        self.label_Login = QtWidgets.QLabel(Form)
        self.label_Login.setGeometry(QtCore.QRect(10, 150, 171, 34))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_Login.setFont(font)
        self.label_Login.setObjectName("label_Login")
        self.label_Parol = QtWidgets.QLabel(Form)
        self.label_Parol.setGeometry(QtCore.QRect(10, 210, 181, 34))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_Parol.setFont(font)
        self.label_Parol.setObjectName("label_Parol")
        self.lineEdit_Login = QtWidgets.QLineEdit(Form)
        self.lineEdit_Login.setGeometry(QtCore.QRect(220, 150, 152, 35))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.lineEdit_Login.setFont(font)
        self.lineEdit_Login.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.lineEdit_Login.setObjectName("lineEdit_Login")
        self.lineEdit_Parol = QtWidgets.QLineEdit(Form)
        self.lineEdit_Parol.setGeometry(QtCore.QRect(220, 210, 152, 35))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.lineEdit_Parol.setFont(font)
        self.lineEdit_Parol.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.lineEdit_Parol.setObjectName("lineEdit_Parol")
        self.pushButton_vioti = QtWidgets.QPushButton(Form)
        self.pushButton_vioti.setGeometry(QtCore.QRect(260, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.pushButton_vioti.setFont(font)
        self.pushButton_vioti.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_vioti.setObjectName("pushButton_vioti")
        self.pushButton_zaregestr = QtWidgets.QPushButton(Form)
        self.pushButton_zaregestr.setGeometry(QtCore.QRect(10, 290, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.pushButton_zaregestr.setFont(font)
        self.pushButton_zaregestr.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_zaregestr.setObjectName("pushButton_zaregestr")
        self.label_pustaia = QtWidgets.QLabel(Form)
        self.label_pustaia.setGeometry(QtCore.QRect(180, 100, 171, 34))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_pustaia.setFont(font)
        self.label_pustaia.setText("")
        self.label_pustaia.setObjectName("label_pustaia")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "avtoriz"))
        self.label_avtorizazia.setText(_translate("Form", "Авторизация"))
        self.label_Login.setText(_translate("Form", "Введите email:"))
        self.label_Parol.setText(_translate("Form", "Введите пароль:"))
        self.pushButton_vioti.setText(_translate("Form", "Войти"))
        self.pushButton_zaregestr.setText(_translate("Form", "Зарегестрироваться"))


class Ui_avtoriz2_ui:
    pass
