# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uslugi_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(539, 491)
        Form.setStyleSheet("background-color: rgb(231, 255, 212);\n"
"")
        self.label_uslugi = QtWidgets.QLabel(Form)
        self.label_uslugi.setGeometry(QtCore.QRect(200, 20, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_uslugi.setFont(font)
        self.label_uslugi.setStyleSheet("")
        self.label_uslugi.setObjectName("label_uslugi")
        self.tableWidget_usl = QtWidgets.QTableWidget(Form)
        self.tableWidget_usl.setGeometry(QtCore.QRect(-10, 310, 551, 192))
        self.tableWidget_usl.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.tableWidget_usl.setObjectName("tableWidget_usl")
        self.tableWidget_usl.setColumnCount(0)
        self.tableWidget_usl.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 250, 302, 38))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout.addWidget(self.pushButton_open)
        self.pushButton_insert = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.pushButton_insert.setFont(font)
        self.pushButton_insert.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.horizontalLayout.addWidget(self.pushButton_insert)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout.addWidget(self.pushButton_delete)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 120, 481, 76))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_uslugi_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_uslugi_2.setFont(font)
        self.label_uslugi_2.setObjectName("label_uslugi_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_uslugi_2)
        self.label_stoimUsl = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.label_stoimUsl.setFont(font)
        self.label_stoimUsl.setObjectName("label_stoimUsl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_stoimUsl)
        self.lineEdit_stoimUsl = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.lineEdit_stoimUsl.setFont(font)
        self.lineEdit_stoimUsl.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.lineEdit_stoimUsl.setObjectName("lineEdit_stoimUsl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_stoimUsl)
        self.lineEdit_usluga = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(16)
        self.lineEdit_usluga.setFont(font)
        self.lineEdit_usluga.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.lineEdit_usluga.setObjectName("lineEdit_usluga")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_usluga)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Uslugi"))
        self.label_uslugi.setText(_translate("Form", "Услуги"))
        self.pushButton_open.setText(_translate("Form", "Открыть"))
        self.pushButton_insert.setText(_translate("Form", "Добавить"))
        self.pushButton_delete.setText(_translate("Form", "Удалить"))
        self.label_uslugi_2.setText(_translate("Form", "Услуга"))
        self.label_stoimUsl.setText(_translate("Form", "Стоимость услуги"))


class Ui_uslugi_ui:
    pass